# Generated by Django 6.0.5 on 2026-05-11 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_apresentacao', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nota_documentacao', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nota_inovacao', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nota_tecnica', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('avaliado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='projetos.projeto')),
            ],
        ),
    ]
